app/app/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # index_page
    path('admin/', admin.site.urls),
    path('map/', include('map.urls')),
    path('tour_data/', include('tour_data.urls')),
    path('festival/', include('festival.urls')),
    path('', views.IndexMain.as_view())
]

festival/urls.py
from django.urls import path
from . import views

app_name = 'festival'

urlpatterns = [
    path('detailview/<int:contentid>/<int:contenttypeid>', views.DetailView.as_view(), name='detailview'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>여행</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        
        {% block styles %}
        {% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">축제</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" href="/map">지도</a></li>
                        {% comment %} <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"></a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li> {% endcomment %}
                    </ul>
                    <span class="time">
                        {% now "Y년 m월 d일 H시 i분" %}
                    </span>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>

        <script src="{% static 'js/base.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<header class="bg-dark py-5 main-bg">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">전국 축제 일정</h1>
            {% comment %} <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p> {% endcomment %}
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-3 justify-content-center loader">
            {% for item in data %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="img-thumbnail card-img-height" src="{{ item.firstimage }}" alt="..."  onclick="ImagePopup('{{ item.firstimage }}');"/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- 제목-->
                            <h5 class="fw-bolder">{{ item.title }}</h5>
                            <!-- 날짜-->
                            <div class="date">
                                {{ item.eventstartdate }}
                                ~
                                {{ item.eventenddate }}
                            </div>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'festival:detailview' contentid=item.contentid contenttypeid=item.contenttypeid %}">자세히보기</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block scripts %}
<!-- main -->
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}